/** @type {import('tailwindcss').Config} */
export default {
    content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: '#e6f1fa',
                    100: '#b3d4f0',
                    200: '#80b7e6',
                    300: '#4d9adc',
                    400: '#267fd4',
                    500: '#0B3D6B',
                    600: '#093461',
                    700: '#072b57',
                    800: '#05224d',
                    900: '#031943',
                },
                teal: {
                    50: '#e6f7f6',
                    100: '#b3e8e4',
                    200: '#80d9d2',
                    300: '#4dcac0',
                    400: '#26bfb3',
                    500: '#0D9488',
                    600: '#0b847a',
                    700: '#09746c',
                    800: '#07645e',
                    900: '#055450',
                },
                nature: {
                    50: '#e8f5e9',
                    100: '#c8e6c9',
                    200: '#a5d6a7',
                    300: '#81c784',
                    400: '#66bb6a',
                    500: '#16A34A',
                    600: '#139240',
                    700: '#108136',
                    800: '#0d702c',
                    900: '#0a5f22',
                },
                accent: {
                    50: '#fff3e0',
                    100: '#ffe0b2',
                    200: '#ffcc80',
                    300: '#ffb74d',
                    400: '#ffa726',
                    500: '#F97316',
                    600: '#e56a10',
                    700: '#d1610a',
                    800: '#bd5804',
                    900: '#a94f00',
                },
                dark: {
                    50: '#f5f5f6',
                    100: '#e0e1e3',
                    200: '#c1c3c7',
                    300: '#a2a5ab',
                    400: '#83878f',
                    500: '#1E293B',
                    600: '#1a2435',
                    700: '#161f2f',
                    800: '#121a29',
                    900: '#0e1523',
                },
            },
            fontFamily: {
                sans: ['Inter', 'system-ui', 'sans-serif'],
                display: ['Poppins', 'system-ui', 'sans-serif'],
            },
            keyframes: {
                'fade-in': {
                    '0%': { opacity: '0', transform: 'translateY(20px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                'fade-in-left': {
                    '0%': { opacity: '0', transform: 'translateX(-30px)' },
                    '100%': { opacity: '1', transform: 'translateX(0)' },
                },
                'fade-in-right': {
                    '0%': { opacity: '0', transform: 'translateX(30px)' },
                    '100%': { opacity: '1', transform: 'translateX(0)' },
                },
                'slide-up': {
                    '0%': { opacity: '0', transform: 'translateY(40px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                'pulse-slow': {
                    '0%, 100%': { opacity: '1' },
                    '50%': { opacity: '0.7' },
                },
                'float': {
                    '0%, 100%': { transform: 'translateY(0px)' },
                    '50%': { transform: 'translateY(-10px)' },
                },
                'pin-drop': {
                    '0%': { transform: 'translateY(-50px)', opacity: '0' },
                    '60%': { transform: 'translateY(5px)', opacity: '1' },
                    '80%': { transform: 'translateY(-3px)' },
                    '100%': { transform: 'translateY(0)' },
                },
                'typing': {
                    '0%': { width: '0' },
                    '100%': { width: '100%' },
                },
                'count-up': {
                    '0%': { opacity: '0', transform: 'scale(0.5)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                'shimmer': {
                    '0%': { backgroundPosition: '-200% 0' },
                    '100%': { backgroundPosition: '200% 0' },
                },
            },
            animation: {
                'fade-in': 'fade-in 0.6s ease-out forwards',
                'fade-in-left': 'fade-in-left 0.6s ease-out forwards',
                'fade-in-right': 'fade-in-right 0.6s ease-out forwards',
                'slide-up': 'slide-up 0.8s ease-out forwards',
                'pulse-slow': 'pulse-slow 3s ease-in-out infinite',
                'float': 'float 3s ease-in-out infinite',
                'pin-drop': 'pin-drop 0.5s ease-out forwards',
                'typing': 'typing 2s steps(30) forwards',
                'count-up': 'count-up 0.5s ease-out forwards',
                'shimmer': 'shimmer 2s linear infinite',
            },
        },
    },
    plugins: [],
};
